# Generated by Django 3.1.6 on 2021-03-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_rate', models.FloatField(default=0.0)),
                ('c_contact_rate', models.FloatField(default=0.0)),
                ('T_transmissibility', models.FloatField(default=0.0)),
                ('R0', models.FloatField(default=0.0)),
                ('new_infected_cases', models.FloatField(default=0.0)),
                ('time', models.IntegerField(default=0)),
                ('new_recovered_cases', models.IntegerField(default=0)),
                ('new_death_cases', models.IntegerField(default=0)),
                ('total_infected_cases', models.IntegerField(default=0)),
                ('total_population', models.IntegerField(default=0)),
                ('m_total_asset', models.IntegerField(default=0)),
                ('s_student_satisfaction', models.IntegerField(default=0)),
                ('death_rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='FixedNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RandomNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
